---
title: "Summarize single-cell data"
author: "Allen Goodman and Shantanu Singh"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Summarize single-cell data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This vignette demonstrates how to summarize single-cell measurements into 
per-well profiles.

## Load data

```{r libraries}
library(magrittr)

```


```{r download, eval=FALSE}
backend <- file.path(tempdir(), "ljosa_jbiomolscreen_2013.sqlite")

download.file("https://s3.amazonaws.com/imaging-platform-collaborator/2016_09_09_cytominr_workshop/ljosa_jbiomolscreen_2013.sqlite",
              backend)

```


```{r load, eval=FALSE}

db <- dplyr::src_sqlite(path = backend)

image <- dplyr::tbl(src = db, "Image")

object <-
  dplyr::tbl(src = db, "Cells") %>%
  dplyr::inner_join(dplyr::tbl(src = db, "Cytoplasm"),
                    by = c("TableNumber", "ImageNumber", "ObjectNumber")) %>%
  dplyr::inner_join(dplyr::tbl(src = db, "Nuclei"),
                    by = c("TableNumber", "ImageNumber", "ObjectNumber"))

object %<>% dplyr::inner_join(image, by = c("TableNumber", "ImageNumber"))

feature_cols <-
  colnames(object) %>%
  stringr::str_subset("^Nuclei_|^Cells_|^Cytoplasm_")
```


## Summarize measurements per well

```{r aggregate, eval=FALSE}
aggregated <-
  cytominr::aggregate(
    population = object,
    variables = feature_cols,
    strata = c("Image_Metadata_Plate", "Image_Metadata_Well"),
    operation = "mean"
  )

aggregated %<>%
  dplyr::collect()

aggregated %>%
  readr::write_csv("ljosa_jbiomolscreen_2013_per_well_mean.csv")
```

## Plot some data

```{r plot, eval=FALSE}
library(ggplot2)

p <- 
  ggplot(aggregated, aes(Cells_AreaShape_Area, Nuclei_AreaShape_Area)) + 
  geom_hex()

print(p)
```

