---
title: "Morphological profiling"
author: "Allen Goodman and Shantanu Singh"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Morphological profiling}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r libraries}
library(magrittr)
library(ggplot2)

```

## Load data

```{r download}
profiles <- readr::read_csv("https://s3.amazonaws.com/imaging-platform-collaborator/2016_09_09_cytominr_workshop/ljosa_jbiomolscreen_2013_per_well_mean.csv")

moa <-
  readr::read_csv("https://data.broadinstitute.org/bbbc/BBBC021/BBBC021_v1_moa.csv") %>%
  dplyr::rename(Image_Metadata_Compound = compound,
                Image_Metadata_Concentration = concentration,
                Image_Metadata_MoA = moa
  )

metadata <-
  readr::read_csv("https://data.broadinstitute.org/bbbc/BBBC021/BBBC021_v1_image.csv") %>%
  dplyr::rename(Image_Metadata_Plate = Image_Metadata_Plate_DAPI,
                Image_Metadata_Well = Image_Metadata_Well_DAPI
  ) %>%
  dplyr::select(dplyr::matches("^Image_Metadata")) %>%
  dplyr::inner_join(moa) %>%
  dplyr::distinct()

profiles %<>%
  dplyr::inner_join(metadata)

feature_cols <-
  colnames(profiles) %>%
  stringr::str_subset("^Nuclei_|^Cells_|^Cytoplasm_")

```


## Filter based on variance

```{r variance_threshold}
profiles <-
  cytominr::select(
    population = profiles,
    variables = feature_cols,
    sample = profiles,
    operation = "variance_threshold"
  ) %>%
  dplyr::collect()

feature_cols <-
  colnames(profiles) %>%
  stringr::str_subset("^Nuclei_|^Cells_|^Cytoplasm_")
```


## Filter based on replicability of features

```{r feature_replicate_scores}
library(foreach)
# library(doMC)
# doMC::registerDoMC()

calculate_feature_replicate_correlations <- 
  function(data, feature_cols, grouping_cols, replicate_count, 
           key_col = NULL, split_col=NULL) {

  calculate_feature_replicate_correlation <- function(data, 
                                                      feature_col, 
                                                      grouping_cols, 
                                                      key_col) {
  
    nonkey_grouping_cols <- setdiff(grouping_cols, key_col)
    
    correlation_matrix <- 
      data %>%
      dplyr::arrange_(.dots = grouping_cols) %>%
      dplyr::select_(.dots = c(grouping_cols, feature_col)) %>% 
      tidyr::spread_(key_col, feature_col) %>% 
      dplyr::select_(~-dplyr::one_of(nonkey_grouping_cols)) %>%
      cor()
    
    median(correlation_matrix[upper.tri(correlation_matrix)])
  }
  
  if (is.null(split_col)) {
    data %<>% dplyr::mutate(split_col = 0) 
    
    split_col <- "split_col"
  }
  
  if (is.null(key_col)) {
    data %<>% 
      dplyr::count_(vars = grouping_cols) %>% 
      dplyr::filter(n == replicate_count) %>% 
      dplyr::select(-n) %>% 
      dplyr::inner_join(data) %>% 
      dplyr::group_by_(.dots = grouping_cols) %>% 
      dplyr::mutate_(.dots = setNames(list(~dplyr::row_number(split_col)), "rep_col")) %>% 
      dplyr::ungroup() 
    
    key_col <- "rep_col"
    
    grouping_cols <- c(grouping_cols, key_col)    
  }

  foreach::foreach(feature_col = feature_cols, .combine = rbind) %dopar%
    {
      
      data %>%
        split(.[split_col]) %>%
        purrr::map_df(calculate_feature_replicate_correlation, 
                      feature_col = feature_col,
                      grouping_cols = grouping_cols,
                      key_col = key_col) %>% 
        dplyr::mutate(feature_col = feature_col)
    } %>%
      tidyr::gather_(key_col, "pearson", setdiff(names(.), "feature_col")) %>% 
      dplyr::group_by_(.dots = c("feature_col")) %>% 
      dplyr::summarize_at("pearson", dplyr::funs(median, min, max))
}

```


```{r feature_replicate_scores_calculate}

feature_replicate_correlations <-
  profiles %>% 
  calculate_feature_replicate_correlations(
    feature_cols = feature_cols,
    grouping_cols = c("Image_Metadata_Compound", "Image_Metadata_Concentration"),
    replicate_count = 3
  )

ggplot(feature_replicate_correlations, aes(median))  + 
  stat_ecdf() + 
  geom_vline(xintercept = 0.6, color = "red") + 
  xlab("median replicate correlation (Pearson)") +
  ylab("F(x)")
  

```


```{r filter_based_on_feature_replicate_correlations}

profiles %<>% 
  dplyr::select_(.dots = 
                   setdiff(x = colnames(profiles), 
                           y = feature_replicate_correlations %>% 
                             dplyr::filter(median < 0.5) %>% 
                             magrittr::extract2("feature_col"))
                 )

feature_cols <-
  colnames(profiles) %>%
  stringr::str_subset("^Nuclei_|^Cells_|^Cytoplasm_")
```


## Filter based on correlation of features

```{r correlation_threshold}
profiles <-
  cytominr::select(
    population = profiles,
    variables = feature_cols,
    sample = profiles,
    operation = "correlation_threshold",
    cutoff = 0.95) %>%
  dplyr::collect()

feature_cols <-
  colnames(profiles) %>%
  stringr::str_subset("^Nuclei_|^Cells_|^Cytoplasm_")
```


## Normalize with reference to DMSO

```{r normalize}

profiles <-
  cytominr::normalize(
    population = profiles,
    variables = feature_cols,
    strata =  c("Image_Metadata_Plate"),
    sample = profiles %>% dplyr::filter(Image_Metadata_Compound == "DMSO")
  )

profiles <-
  cytominr::select(
      population = profiles,
      variables = feature_cols,
      operation = "drop_na_columns"
  )

feature_cols <-
  colnames(profiles) %>%
  stringr::str_subset("^Nuclei_|^Cells_|^Cytoplasm_")

```


## Calculate treatment profiles

```{r treatment_profiles}

profiles <-
  cytominr::aggregate(
    population = profiles,
    variables = feature_cols,
    strata = c("Image_Metadata_Compound", 
               "Image_Metadata_Concentration",
               "Image_Metadata_MoA"),
    operation = "mean"
  )
```


## Predict MoA

```{r predict_moa}
profiles %<>% 
  dplyr::filter(Image_Metadata_Compound != "DMSO") 
  
cor_mat <- 
  profiles %>%
  dplyr::select(dplyr::one_of(feature_cols)) %>% 
  as.matrix() %>% 
  t() %>%
  cor()

cpd <- profiles$Image_Metadata_Compound

mask <- as.integer(outer(cpd, cpd, FUN="!="))

mask[mask == 0] <- -Inf
  
cor_mat <- cor_mat * mask

moa <- as.character(profiles$Image_Metadata_MoA)

pred <- sapply(1:nrow(cor_mat), 
               function(i) moa[order(cor_mat[i,], decreasing = TRUE)[1]])

caret::confusionMatrix(pred, moa)
  
```

