---
title: "Predict compounds mechanism-of-action by morphological profiling"
author: "Allen Goodman and Shantanu Singh"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Predict compounds mechanism-of-action by morphological profiling}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r libraries, message=FALSE}
library(cytominrworkshop)
library(dplyr)
library(magrittr)
library(ggplot2)
library(stringr)

```

## Load data

```{r download, message=FALSE}


profiles <- 
  readr::read_csv(system.file("extdata", "ljosa_jbiomolscreen_2013_per_well_mean.csv", 
                package = "cytominrworkshop"))

moa <-
  readr::read_csv(system.file("extdata", "BBBC021_v1_moa.csv", 
                              package = "cytominrworkshop")) %>%
  rename(Image_Metadata_Compound = compound,
                Image_Metadata_Concentration = concentration,
                Image_Metadata_MoA = moa
  )

metadata <-
  readr::read_csv(system.file("extdata", "BBBC021_v1_image.csv", 
                              package = "cytominrworkshop")) %>%
  rename(Image_Metadata_Plate = Image_Metadata_Plate_DAPI,
                Image_Metadata_Well = Image_Metadata_Well_DAPI
  ) %>%
  select(matches("^Image_Metadata")) %>%
  inner_join(moa) %>%
  distinct()

profiles %<>%
  inner_join(metadata)

variables <-
  colnames(profiles) %>%
  str_subset("^Nuclei_|^Cells_|^Cytoplasm_")

```


## Filter based on variance

```{r variance_threshold, message=FALSE}
profiles <-
  cytominr::select(
    population = profiles,
    variables = variables,
    sample = profiles,
    operation = "variance_threshold"
  ) %>%
  collect()

variables <-
  colnames(profiles) %>%
  str_subset("^Nuclei_|^Cells_|^Cytoplasm_")
```


## Filter based on replicability of features


```{r feature_replicate_scores_calculate, fig.width=4, fig.height=4, message=FALSE}

doParallel::registerDoParallel(cores = 2)

feature_replicate_correlations <-
  profiles %>% 
  variable_quality(
    variables = variables,
    strata = c("Image_Metadata_Compound", "Image_Metadata_Concentration"),
    replicates = 3
  )

ggplot(feature_replicate_correlations, aes(median))  + 
  stat_ecdf() + 
  geom_vline(xintercept = 0.6, color = "red") + 
  xlab("median replicate correlation (Pearson)") +
  ylab("F(x)")
  

```


```{r filter_based_on_feature_replicate_correlations, message=FALSE}

profiles %<>% 
  select_(.dots = setdiff(x = colnames(profiles), 
                          y = feature_replicate_correlations %>% 
                            filter(median < 0.5) %>% 
                            magrittr::extract2("variable"))
          )

variables <-
  colnames(profiles) %>%
  str_subset("^Nuclei_|^Cells_|^Cytoplasm_")
```


## Filter based on correlation of features

```{r correlation_threshold, message=FALSE}
profiles <-
  cytominr::select(
    population = profiles,
    variables = variables,
    sample = profiles,
    operation = "correlation_threshold",
    cutoff = 0.95) %>%
  collect()

variables <-
  colnames(profiles) %>%
  str_subset("^Nuclei_|^Cells_|^Cytoplasm_")
```


## Normalize with reference to DMSO

```{r normalize, message=FALSE}

profiles <-
  cytominr::normalize(
    population = profiles,
    variables = variables,
    strata =  c("Image_Metadata_Plate"),
    sample = profiles %>% filter(Image_Metadata_Compound == "DMSO")
  )

profiles <-
  cytominr::select(
      population = profiles,
      variables = variables,
      operation = "drop_na_columns"
  )

variables <-
  colnames(profiles) %>%
  str_subset("^Nuclei_|^Cells_|^Cytoplasm_")

```


## Calculate treatment profiles

```{r treatment_profiles, message=FALSE}

profiles <-
  cytominr::aggregate(
    population = profiles,
    variables = variables,
    strata = c("Image_Metadata_Compound", 
               "Image_Metadata_Concentration",
               "Image_Metadata_MoA"),
    operation = "mean"
  )
```


## Predict MoA

```{r predict_moa, message=FALSE}
profiles %<>% 
  filter(Image_Metadata_Compound != "DMSO") 
  
correlation <- 
  profiles %>%
  select(one_of(variables)) %>% 
  as.matrix() %>% 
  t() %>%
  cor()

compound <- profiles$Image_Metadata_Compound

mask <- as.integer(outer(compound, compound, FUN="!="))

mask[mask == 0] <- -Inf
  
correlation_masked <- correlation * mask

mechanism <- as.character(profiles$Image_Metadata_MoA)

prediction <- sapply(1:nrow(correlation_masked), 
               function(i) mechanism[order(correlation_masked[i,], 
                                           decreasing = TRUE)[1]])

confusion_matrix <- caret::confusionMatrix(prediction, mechanism)

tibble::frame_data(
  ~metric, ~value,
  "Accuracy", sprintf("%.2f", confusion_matrix$overall["Accuracy"]), 
  "95% CI", sprintf("(%.2f, %.2f)", confusion_matrix$overall[["AccuracyLower"]], confusion_matrix$overall[["AccuracyUpper"]])
) %>% knitr::kable(digits = 2)

confusion_matrix$table %>% 
  knitr::kable()

```


```{r tsne, fig.width=8, fig.height=6, message=FALSE}

set.seed(123)

df <- 
  tibble::as_data_frame(
    tsne::tsne(as.dist(1-correlation))
    ) %>% 
  mutate(mechanism = mechanism)

p <- 
  ggplot(df, aes(V1, V2, color=mechanism)) + 
  geom_point() + 
  ggtitle("t-SNE visualization of compound profiles")

print(p)

```

