---
title: "Analyze single-cell data"
author: "Allen Goodman and Shantanu Singh"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Analyze single-cell data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This vignette demonstrates how to summarize single-cell measurements into 
per-well profiles. It assumes that <https://s3.amazonaws.com/imaging-platform-collaborator/2016_09_09_cytominr_workshop/ljosa_jbiomolscreen_2013.sqlite> has been downloaded into a directory named `Downloads` in the home directory.

## Load data

```{r libraries, message=FALSE}
library(dplyr)
library(ggplot2)
library(magrittr)

```


```{r load, message=FALSE}

backend <- file.path(Sys.getenv("HOME"), "Downloads", "ljosa_jbiomolscreen_2013.sqlite")

db <- src_sqlite(path = backend)

image <- tbl(src = db, "Image")

object <-
  tbl(src = db, "Cells") %>%
  inner_join(tbl(src = db, "Cytoplasm"),
                    by = c("TableNumber", "ImageNumber", "ObjectNumber")) %>%
  inner_join(tbl(src = db, "Nuclei"),
                    by = c("TableNumber", "ImageNumber", "ObjectNumber"))

object %<>% inner_join(image, by = c("TableNumber", "ImageNumber"))

variables <-
  colnames(object) %>%
  stringr::str_subset("^Nuclei_|^Cells_|^Cytoplasm_")
```


## Summarize measurements per well

```{r aggregate, message=FALSE}
profiles <-
  cytominr::aggregate(
    population = object,
    variables = variables,
    strata = c("Image_Metadata_Plate", "Image_Metadata_Well"),
    operation = "mean"
  )

profiles %<>%
  collect()

profiles %>%
  readr::write_csv("ljosa_jbiomolscreen_2013_per_well_mean.csv")
```

## Plot data

```{r plot, fig.width=6, fig.height=5, message=FALSE}
p <- 
  ggplot(profiles, aes(Cells_AreaShape_Area, Nuclei_AreaShape_Area)) + 
  geom_hex()

print(p)
```

