# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' online_covar
#'
#' @param x1 a numeric vector containing samples of the first random variable
#' @param x2 a numeric vector containing corresponding samples of the second random variable
#'
#' @export
#'
online_covar <- function(x1, x2) {
    .Call('cytominergallery_online_covar', PACKAGE = 'cytominergallery', x1, x2)
}

#' two_pass_multi_covar
#'
#' @param s a data matrix whose column covariances are sought
#'
#' @export
#'
two_pass_multi_covar <- function(s) {
    .Call('cytominergallery_two_pass_multi_covar', PACKAGE = 'cytominergallery', s)
}

#' combine_cov_estimates
#'
#' @param batch_mean_cov the matrix which contains estimated means and covariance for each batch of data.
#'         For n variable, and k batches, it is (n+1)*(n.k) size, with the first row being the means and
#'         rest of the rows being the covariance matrices. Covariance matrices were concatenated column-wise
#'         resulting in n.k columns.
#' @param b a vector containing number of samples in each batch of data
#'
#' @export
#'
combine_cov_estimates <- function(batch_mean_cov, b) {
    .Call('cytominergallery_combine_cov_estimates', PACKAGE = 'cytominergallery', batch_mean_cov, b)
}

