# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' custom_covar
#' 
#' @param x1 ...
#' @param x2 ...
#' 
#' @export
#' 
custom_covar <- function(x1, x2) {
    .Call('cytominergallery_custom_covar', PACKAGE = 'cytominergallery', x1, x2)
}

#' combine_covs
#' 
#' @param s ...
#' 
#' @export
#' 
custom_multi_covar <- function(s) {
    .Call('cytominergallery_custom_multi_covar', PACKAGE = 'cytominergallery', s)
}

#' combine_covs_base
#' 
#' @param mn_covs1 ...
#' @param mn_covs2 ...
#' @param ns1 ...
#' @param ns2 ...
#' 
#' @export
#' 
combine_covs_base <- function(mn_covs1, mn_covs2, ns1, ns2) {
    .Call('cytominergallery_combine_covs_base', PACKAGE = 'cytominergallery', mn_covs1, mn_covs2, ns1, ns2)
}

#' combine_covs
#' 
#' @param mn_covs ...
#' @param ns ...
#' 
#' @export
#' 
combine_covs <- function(mn_covs, ns) {
    .Call('cytominergallery_combine_covs', PACKAGE = 'cytominergallery', mn_covs, ns)
}

